<!DOCTYPE html>
<html>
<head>
    <title>Kind Servlet</title>
</head>
<body>

<form action="/infoShareAcademy" method="post">
    Parametr 1:
    <input type="text" name="param1"><br>
    Parametr 2:
    <input type="text" name="param2"><br>
    Parametr 3:
    <input type="text" name="param3"><br>
    Parametr 3:
    <input type="text" name="param3"><br>
    <input type="submit" value="Wyslij">
</form>

</body>
</html>